server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: neuro
    password: 123456
    driver-class-name: org.postgresql.Driver


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰转换
  global-config:
    db-config:
      # 插入和更新时，只要 Java 字段是 null，就不往 SQL 里拼这个字段！
      insert-strategy: not_null
      update-strategy: not_null
