server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neuro_note
    username: neuro
    password: 123456
    driver-class-name: org.postgresql.Driver

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # 开启控制台打印 SQL 语句（排错神器）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
